### ISSUE TITLE
In GORM for MongoDB, some features won't work unless you use MongoSpec

### ISSUE THREAD

**Issue by alvarosanchez** [grails/grails-testing-support#13]
I'm not sure whether this is an actual issue we can improve, or simply something we can clarify in the documentation.

The issue is that with a standard mocking from `DomainUnitTest` or `DataTest`, some GORM features are not working, like the default sort order defined in `mapping{}`. I think the reason why is because a `MongoDatastore` is required instead of `SimpleMapDatastore`. But maybe the reason is different.

In order for such GORM form MongoDB features to work, one needs to extend from `grails.test.mongodb.MongoSpec`, and forget about `DomainUnitTest` or `DataTest` mocking.

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails/grails-data-mapping/commit/ae0e94733e4ec89f5f0e63dd1de80f9716bbc3ce
