### ISSUE TITLE
Documentation on website is missing code segments

### ISSUE THREAD

**Issue by Oribow** [grails/grails-testing-support#151]
Hi,

the documentation on the website is missing the code segments. 

[https://testing.grails.org/latest/guide/index.html#unitTestingServices](https://testing.grails.org/latest/guide/index.html#unitTestingServices)

![image](https://user-images.githubusercontent.com/17454603/139860497-23907fbe-1a59-4a5a-92b0-fe7d55f7540b.png)

**Comment by puneetbehl** [comment]
Thank you for reporting the issue. I think this has been resolved.
