### ISSUE TITLE
The documentation is broken; none of the examples are showing up

### ISSUE THREAD

**Issue by kc13greiner** [grails/grails-testing-support#159]
I am trying to read the documentation [here](https://testing.grails.org/latest/guide/index.html), but all of the code snippets are showing errors. 

<img width="1248" alt="Screen Shot 2021-11-16 at 10 30 34 AM" src="https://user-images.githubusercontent.com/21210601/142015053-a38228a1-31f1-45b0-b61f-4971c10b3232.png">

**Comment by matrei** [comment]
Fixed in #160
