### ISSUE TITLE
dataStore vs datastore

### ISSUE THREAD

**Issue by basejump** [grails/grails-testing-support#22]
dataStore is camel case in DataTest when is all lower case everywhere else in gorm. 
gets a bit confusing. 
getDataStore here should be renamed to getDatastore() here
https://github.com/grails/grails-testing-support/blob/master/grails-gorm-testing-support/src/main/groovy/grails/testing/gorm/DataTest.groovy#L105

**Comment by jameskleeh** [comment]
I think you are right, however that would be a breaking change which I cannot do at this time.
