### ISSUE TITLE
JSON converters not working in ServiceUnitTest

### ISSUE THREAD

**Issue by ayZagen** [grails/grails-testing-support#37]
When trying to test a grails service which uses `JSON` converter throws error.

Exception message is :  org.grails.web.converters.exceptions.ConverterException: Unconvertable Object of class: java.util.LinkedHashMap

**Comment by ayZagen** [comment]
I should have implemented `GrailsWebUnitTest`

**Comment by wangyepeng2** [comment]
I solve it  by implemented GrailsWebUnitTest ,thank you

**Comment by urmichm** [comment]
GrailsWebUnitTest throws initiaalizationError
