### ISSUE TITLE
Integration test performance degradation compared to grails-test-mixin-plugin

### ISSUE THREAD

**Issue by dpcasady** [grails/grails-testing-support#44]
After upgrading an app from Grails 3.2.x to 3.3.x I noticed that integration tests take a lot longer to run. 

The old test plugin [has a dependency on spring-boot-starter-test](https://github.com/grails-plugins/grails-test-mixin-plugin/blob/master/build.gradle#L78) which includes mockito-core. Since the new testing framework does not have that dependency, mockito isn't included and it seems as though that is the source of the slowdown. Honestly I have no idea why including mockito-core would affect integration tests, but it does.

To illustrate the difference in performance, an empty Grails 3.3 app runs the following integration test roughly 3x faster if mockito-core is included as a dependency:

```groovy
@Unroll
void "this test runs faster with mockito"() {
    expect:
    1

    where:
    a << Arrays.asList(new Integer[100]) // run test 100 times
}
```

Here's a sample project: https://github.com/dpcasady/integration-test-perf

The sample project has a testCompile dependency on mockito-core that is commented out. Run the integration tests to get a sense of the execution time, then uncomment the mockito dependency and run the tests again.

I'm not sure if the new testing framework should include mockito by default, I just thought such a big difference in test execution time should be noted.

**Comment by niravassar** [comment]
@dpcasady thanks for posting the sample project. In the integration test there is a comment `// run test 100 times`. Does it mean to instruct to run it 100 times manually? or does this somehow loop 100 times.

**Comment by dpcasady** [comment]
That line serves as a data provider. When used with the `@Unroll` annotation it will essentially loop that test 100 times. No need to do anything manually!

**Comment by niravassar** [comment]
ok yes i see you are using a as a var in @Unroll to spawn the spock tests.

**Comment by niravassar** [comment]
@graemerocher and @jameskleeh 

I have reproduced what danny has demonstrated in the test project. I think mockito is doing some compile time optimizations to increase performance. On the particular test without mockito `testCompile` the test will run at 1min. With mockito `testCompile` it reduces the time to 20 seconds. 

I looked through the jar briefly and it has a few packages and a lot of code on asm and transformers. Of course I don't expect to understand how this is occurring. 

Would you mind taking a look and should we consider making this a dependency, or somehow incorporating this in to Grails?

**Comment by niravassar** [comment]
I created a PR in base profile repo that would add mockito as a dependency. This is given my assumptions are correct
