### ISSUE TITLE
Incorrect validation when using deepValidate:false

### ISSUE THREAD

**Issue by ernesto-castelan** [grails/grails-testing-support#45]
For unit tests, using `validate(deepValidate:false)` on already persisted domains, sometimes return an incorrect result.

For example, for the following domain
```groovy
class Example {

    Boolean alpha
    Boolean beta
    String sigma

    static constraints = {
        isValid notEqual:false
        sigma   notEqual:'bad'
    }

    Boolean getIsValid() {
        alpha || beta
    }
}
```

These tests fail as unit tests (because `validate` returns true) but pass as integration tests 
```groovy
    void "Test isValid for saved instance"() {
        given:
            new Example(alpha:true, beta:true, sigma:'good').save(flush:true)
            assert Example.count() == 1

        when:
            Example example = Example.first()
            example.alpha = false
            example.beta = false

        then:
            !example.validate(deepValidate:false)
            example.errors.getFieldError('isValid').code == 'notEqual'
    }

    void "Test sigma for saved instance"() {
        given:
            new Example(alpha:true, beta:true, sigma:'good').save(flush:true)
            assert Example.count() == 1

        when:
            Example example = Example.first()
            example.sigma = 'bad'

        then:
            !example.validate(deepValidate:false)
            example.errors.getFieldError('sigma').code == 'notEqual'
    }
```

You will find the relevant tests in the Grails 3.3.8 sample project, in the files `ExampleSpec.groovy` and `ExampleIntegrationSpec.groovy`
[strange_validation.zip](https://github.com/grails/grails-testing-support/files/2521084/strange_validation.zip)

Thanks in advance

**Comment by puneetbehl** [comment]
I believe this is happening because of `skipValidate` set to `true` ([here](https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm/src/main/groovy/org/grails/datastore/gorm/GormInstanceApi.groovy#L339)) and this seems to be intentional to avoid frequent `validation` checks. 

In order to make this test work, you can `implement DataTest` and then update your tests as:

```
void "Test sigma for saved instance"() {
        given:
            new Example(alpha:true, beta:true, sigma:'good').save(flush:true)
            assert Example.count() == 1
            session.flush()
            session.clear()

        when:
            Example example = Example.first()
            example.sigma = 'bad'

        then:
            !example.validate(deepValidate:false)
            example.errors.getFieldError('sigma').code == 'notEqual'
    }

    private Session getSession() {
        dataStore.currentSession
    }
```

**Comment by ernesto-castelan** [comment]
Your solution works well. I used the `currentSession` property instead, directly from `DataTest` with the same result. Thank you!
