### ISSUE TITLE
Query: How to run integration test classes sequentially in grails(spock)

### ISSUE THREAD

**Issue by sadasivaiahgoli** [grails/grails-testing-support#47]
Iam using spock in my grails project. I wan to run the test classes in a sequence order. When I run all the test cases in a package it runs randomly. I am using linux os. How can we run the test classes in a sequence order. Or How to define test suit in spock .

**Comment by puneetbehl** [comment]
Please use stackoverflow or Grails slack for questions. 

I think you should try not to go down that path. Your Specification should be independent of others. Read more about in following [Stackoverflow question](https://stackoverflow.com/questions/48986072/how-to-tell-spock-which-class-to-run-in-specific-order)

**Comment by sadasivaiahgoli** [comment]
Ok thanks puneetbehi. I will try .

**Comment by sadasivaiahgoli** [comment]
I found the command for running test suite. Thanks puneetbehi
