### ISSUE TITLE
@TestFor(Domain) class exposed domain property, DomainUnitTest does not

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-testing-support#6]
You used to be able to do: 

```
@TestFor(Book) 
class BookSpec extends Specification {
    def "validate is not nullable"() {
         when:
         domain.name = null
         def result = domain.validate(['name'])

         then:
         !result
    }
}
```

`DomainUnitTest` does not instantiate domain property as old `@TestFor` annotation did. 

Workaround: 

```
class BookSpec extends Specification implements DomainUnitTest<Book> {

    @Subject
    Book domain
    def setup() {
        domain = new Book()
    }

    def "validate is not nullable"() {
         when:
         domain.name = null
         def result = domain.validate(['name'])

         then:
         !result
    }
}
```

Or a solution could be to  implement something like 

`T getDomain() `

as the ControllerUnitTest does:

https://github.com/grails/grails-testing-support/blob/master/grails-web-testing-support/src/main/groovy/grails/testing/web/controllers/ControllerUnitTest.groovy#L82

**Comment by erichelgeson** [comment]
Just ran into this as well - Since everything is a Trait I mixed two together to get this behavior
```groovy
trait OneDomainTest<T> implements DataTest, ParameterizedGrailsUnitTest<T> {
    T getDomain() { 
        getArtefactInstance() 
    }
    void mockArtefact(Class<?> artefactClass) { 
        mockDomain(artefactClass) 
    }
}
```
I can see where you would not want to do this if there was a list of domains to mock for, but I'd be nice to have the same functionality to not re-write tests.
