### ISSUE TITLE
@Rollback annotation doesn't work in integration test

### ISSUE THREAD

**Issue by chris13524** [grails/grails-testing-support#9]
I'm writing an integration test to test my "JSON" (in the real app it is) API.

I have a simple domain `class User { String email }` and a controller that checks for duplicate emails before creation. I have two integration tests that both do the same thing, make a GET request and check `response.status == 201` and `User.count == 1`.

Currently, I have these two tests in separate files, `UserSpec` and `UserSpecAgain`. You could put both tests in the same class and it will cause the same issue. For me, `UserSpecAgain` runs first and it passes fine, and then `UserSpec` runs, but the domain wasn't cleared so that test fails due to a duplicate email.

I have the `@Rollback` annotation on both my test specs, but it doesn't seem anything gets rolled back.

These integration tests never worked right for me (even on the old framework). I thought they were just like unit tests, but without the need to mock anything, etc. Maybe I was wrong on my assumption. Functional tests seem to lack good documentation so I'm just piecing stuff together.

[testing-demo.zip](https://github.com/grails/grails-testing-support/files/1126625/testing-demo.zip)

**Comment by sdelamo** [comment]
`@Rollback` annotation wraps a feature method in a transaction. If you create a user inside the method, the user will be rollbacked:

```
@Rollback
def "This use will be rollbacked"() {
    when:
    def u = new User(email:'me@email.com')
    u.save()

    then:
    User.count() == old(User.count()) + 1
}
```

However, when you invoke your app with RestBuilder you are calling your app from the outside. The transaction of the feature method will not be the same transaction as in the app. Thus, the side effects of the endpoint invocation will not be rollbacked by the annotation.  You will need to revert the side effects manually. You could do something like this in the `cleanup` phase of the feature method.

```
package coconut.integrationtest

import coconut.UserService
import grails.plugins.rest.client.RestBuilderg
import grails.plugins.rest.client.RestResponse
import grails.testing.mixin.integration.Integration
import spock.lang.Specification

@Integration
class UserSpec extends Specification {
	private static final String USER_EMAIL = "joe@example.com"

	UserService userService
	
	void "create user"() {
		when:
		RestResponse response = new RestBuilder().post("http://localhost:$serverPort/user") {
			json([
				email: USER_EMAIL
			])
		}
		
		then:
		response.status == 201
		userService.userCount() == 1

		cleanup:
		userService.deleteByEmail(USER_EMAIL)
	}
}

```

I have created  a sample repository:

https://github.com/grails-core-issues-forks/grails-testing-support-issues-9-


You can run the tests with `./gradlew iT`

Note: your attached example did not use `@Transactional `in the Controller. You should wrap your GORM logic in transactions. Moreover, I have moved all your logic to a service, annotated with `@Transactional `and` @ReadOnly` when necessary and with `@CompileStatic. `
